### ISSUE TITLE
Cannot find module 'joi' after upgrade to 1.4.0

### ISSUE THREAD

**Issue by Alwe** [RobinCK/typeorm-fixtures#81]
I upgraded to 1.4.0 and get a "Cannot find module 'joi' after upgrade to 1.4.0" error when running `fixtures`.
When searching for the usage of the removed dependency joi I find it in typeorm-fixtures-cli/dist/schema/jFixturesSchema.js and .../dist/Loader
The typeorm-fixtures-cli/package.json has the correct version of 1.4.0 though with @hapi/joi in dependencies.

It seems like the npm package ships with an old version of the source code.

**Comment by RobinCK** [comment]
please try v1.4.2

**Comment by Alwe** [comment]
Works fine now.
Thanks a lot.
